# Generated by Django 5.2 on 2026-08-31 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('files', '0002_alter_files_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.files')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
            options={
                'db_table': 'fileshare',
            },
        ),
    ]
