# Generated by Django 5.2 on 2026-08-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folders')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
