# Generated by Django 5.2 on 2026-08-26 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folders'),
        ),
    ]
