# Generated by Django 5.2 on 2026-08-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.users')),
                ('pparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folders')),
            ],
            options={
                'db_table': 'folders',
            },
        ),
    ]
