# Generated by Django 5.2 on 2026-08-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folders',
            old_name='pparent',
            new_name='parent',
        ),
    ]
