# Generated by Django 5.2 on 2026-08-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_rename_pparent_folders_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
